#!/usr/bin/env bash
# ============================================================
# OpenServe OS — New Tenant Onboarding Script
#
# Usage:  ./scripts/new-tenant.sh <tenant-slug> [admin-username]
# Example: ./scripts/new-tenant.sh bellavista-luzern admin
#
# What it does:
#   1. Creates tenants/<slug>/ directory with docker-compose + .env
#   2. Generates secure random secrets (DB password, JWT secret)
#   3. Starts the stack (postgres, redis, backend, frontend)
#   4. Runs all migrations
#   5. Creates the initial admin user with a generated PIN
#   6. Prints a handover summary with login credentials
# ============================================================
set -euo pipefail

# ── helpers ──────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}ℹ${NC}  $*"; }
success() { echo -e "${GREEN}✅${NC}  $*"; }
warn()    { echo -e "${YELLOW}⚠️${NC}  $*"; }
error()   { echo -e "${RED}❌${NC}  $*"; exit 1; }

# ── args ─────────────────────────────────────────────────────
SLUG="${1:-}"
ADMIN_USER="${2:-admin}"
[[ -z "$SLUG" ]] && error "Usage: $0 <tenant-slug> [admin-username]\n  Example: $0 bellavista-luzern"

REPO_ROOT="$(dirname "$0")/.."
TENANTS_DIR="${REPO_ROOT}/tenants/${SLUG}"

[[ -d "$TENANTS_DIR" ]] && error "Tenant '${SLUG}' already exists at ${TENANTS_DIR}"

# ── port allocation (base 3000, each tenant +10) ─────────────
EXISTING=$(ls "${REPO_ROOT}/tenants" 2>/dev/null | wc -l)
BACKEND_PORT=$((3000 + (EXISTING + 1) * 10))
FRONTEND_PORT=$((80   + (EXISTING + 1)))    # 81, 82, 83 …

# ── generate secrets ─────────────────────────────────────────
gen_secret() { openssl rand -base64 32 | tr -d '/+=' | head -c 40; }
gen_pin()    { printf '%04d' $((RANDOM % 10000)); }

DB_NAME="openserve_${SLUG//-/_}"
DB_USER="pos_${SLUG//-/_}"
DB_PASSWORD=$(gen_secret)
JWT_SECRET=$(gen_secret)
ADMIN_PIN=$(gen_pin)

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════${NC}"
echo -e "${BLUE}  OpenServe OS — New Tenant Setup${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════${NC}"
info "Tenant slug   : ${SLUG}"
info "Backend port  : ${BACKEND_PORT}"
info "Frontend port : ${FRONTEND_PORT}"
info "DB name       : ${DB_NAME}"
echo ""

# ── create tenant directory ──────────────────────────────────
mkdir -p "$TENANTS_DIR"

# ── write .env ───────────────────────────────────────────────
cat > "${TENANTS_DIR}/.env" <<EOF
# Auto-generated by new-tenant.sh — $(date)
TENANT_SLUG=${SLUG}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
JWT_SECRET=${JWT_SECRET}
BACKEND_PORT=${BACKEND_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
NODE_ENV=production
# Add your Sentry DSN here once you have one:
SENTRY_DSN=
VITE_SENTRY_DSN=
EOF

success ".env generated"

# ── write docker-compose.yml ─────────────────────────────────
cat > "${TENANTS_DIR}/docker-compose.yml" <<EOF
# OpenServe OS — Tenant: ${SLUG}
# Generated: $(date)
services:
  postgres-${SLUG}:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_${SLUG//-/_}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis-${SLUG}:
    image: redis:7-alpine
    restart: unless-stopped

  backend-${SLUG}:
    image: ghcr.io/jonasstreule/openserve-os-backend:latest
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres-${SLUG}:5432/${DB_NAME}
      REDIS_URL: redis://redis-${SLUG}:6379
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      SENTRY_DSN: \${SENTRY_DSN:-}
    depends_on:
      postgres-${SLUG}:
        condition: service_healthy
    restart: unless-stopped

  frontend-${SLUG}:
    image: ghcr.io/jonasstreule/openserve-os-frontend:latest
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      VITE_API_URL: http://localhost:${BACKEND_PORT}
      VITE_SENTRY_DSN: \${VITE_SENTRY_DSN:-}
    depends_on:
      - backend-${SLUG}
    restart: unless-stopped

volumes:
  postgres_data_${SLUG//-/_}:
EOF

success "docker-compose.yml generated"

# ── start the stack ──────────────────────────────────────────
info "Starting Docker stack…"
cd "$TENANTS_DIR"
docker compose up -d

# ── wait for backend to be ready ─────────────────────────────
info "Waiting for backend to be healthy…"
BACKEND_URL="http://localhost:${BACKEND_PORT}"
for i in $(seq 1 30); do
  if curl -sf "${BACKEND_URL}/api/health" > /dev/null 2>&1; then
    success "Backend is up"
    break
  fi
  [[ $i -eq 30 ]] && error "Backend did not start within 60 s — check: docker compose -f ${TENANTS_DIR}/docker-compose.yml logs"
  sleep 2
done

# ── run migrations ────────────────────────────────────────────
MIGRATIONS_DIR="${REPO_ROOT}/migrations"
DB_CONTAINER="postgres-${SLUG}"
info "Running migrations…"

for sql in "${MIGRATIONS_DIR}"/*.sql; do
  FNAME=$(basename "$sql")
  docker compose exec -T "${DB_CONTAINER}" \
    psql -U "${DB_USER}" -d "${DB_NAME}" -f - < "$sql" > /dev/null
  echo "    ✓ ${FNAME}"
done

success "All migrations applied"

# ── create admin user ─────────────────────────────────────────
info "Creating admin user '${ADMIN_USER}'…"
PIN_HASH=$(node -e "const b=require('bcryptjs'); b.hash('${ADMIN_PIN}',10).then(h=>process.stdout.write(h))" 2>/dev/null)

docker compose exec -T "${DB_CONTAINER}" \
  psql -U "${DB_USER}" -d "${DB_NAME}" \
  -c "INSERT INTO users (username, pin_hash, role) VALUES ('${ADMIN_USER}','${PIN_HASH}','admin') ON CONFLICT DO NOTHING;" \
  > /dev/null

success "Admin user created"

# ── backup cron hint ──────────────────────────────────────────
CRON_LINE="0 3 * * *  DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME} ${REPO_ROOT}/scripts/backup.sh ${SLUG}"

# ── handover summary ─────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ Tenant '${SLUG}' is live!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${YELLOW}Frontend URL${NC}   http://localhost:${FRONTEND_PORT}"
echo -e "  ${YELLOW}Backend API${NC}    http://localhost:${BACKEND_PORT}"
echo -e "  ${YELLOW}Health check${NC}   http://localhost:${BACKEND_PORT}/api/health"
echo ""
echo -e "  ${YELLOW}Admin login${NC}"
echo -e "    Username : ${ADMIN_USER}"
echo -e "    PIN      : ${ADMIN_PIN}"
echo ""
echo -e "  ${YELLOW}Automated daily backup (add to crontab)${NC}"
echo -e "    ${CRON_LINE}"
echo ""
echo -e "  ${YELLOW}Manage stack${NC}"
echo -e "    cd ${TENANTS_DIR}"
echo -e "    docker compose logs -f"
echo -e "    docker compose down"
echo ""
echo -e "  ${YELLOW}Tenant config${NC}   ${TENANTS_DIR}/.env"
echo ""
